metric_report:
    resource: "@MetricReportBundle/Controller/"
    type:     annotation
    prefix:   /

covise:
    resource: "@CoviseBundle/Controller/"
    type:     annotation
    prefix:   /

administration:
    resource: "@AdministrationBundle/Controller/"
    type:     annotation
    prefix:   /

experiment:
    resource: "@ExperimentBundle/Resources/config/routing.yml"
    prefix:   /

cool_em_all_user:
    resource: "@CoolEmAllUserBundle/Controller/"
    type:     annotation
    prefix:   /

DebbConfigBundle:
    resource: "@DebbConfigBundle/Resources/config/routing.yml"

DebbManagementBundle:
    resource: "@DebbManagementBundle/Resources/config/routing.yml"

CIMPluploadBundle:
    resource: "@CIMPluploadBundle/Controller/"
    type:     annotation
    prefix:   /plupload

_imagine:
    resource: .
    type: imagine

_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

psnc_mopgui:
    resource: "@PsncMopguiBundle/Resources/config/routing.yml"

psnc_dcworms:
    resource: "@PsncDcwormsBundle/Resources/config/routing.yml"
