<?php

namespace Hlrs\ExperimentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExperimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperimentRepository extends EntityRepository
{
}
