parameters:
#    acme_hello.example.class: Acme\HelloBundle\Example

services:
#    acme_hello.example:
#        class: %acme_hello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    hlrs.administration.menu.voter.request:
        class: Hlrs\AdministrationBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }
            
#parameters:
#    experiment.example.class: Hlrs\ExperimentBundle\Example

#services:
    #hlrs.administration.menu.voter.request:
    #    class: Hlrs\AdministrationBundle\Menu\RequestVoter
    #    arguments:
    #        - "@service_container"
    #    tags:
    #        - { name: knp_menu.voter }